version: "2"
services:
  app:
    user: "503:20"
    container_name: app
    restart: always
    build: .
    volumes:
      - ./app:/app
      - ./app:/app/node_modules
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
  mongo:
    user: "503:20"
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"